# Generated by Django 3.0.7 on 2024-01-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndirimKuponu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('indirim_orani', models.FloatField()),
                ('son_kullanma_tarihi', models.DateField()),
            ],
        ),
    ]
